In [1]:
from os import listdir
from os.path import isfile, join
def dfile (path):
    mypath = path
    onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
    return onlyfiles

In [2]:
import pandas as pd
import numpy as np

# Load Kunci Jawaban

In [3]:
df = pd.read_excel("data\kunci jawaban dosen\kunci_jawaban_dosen.xlsx")
kode = df.kode.tolist()
skor = df.skor.tolist()
kunci_jawaban = df.jawaban_jawaban.tolist()

dict_kunci_jawaban = dict(zip(kode, kunci_jawaban))
dict_skor = dict(zip(kode, skor))
dict_skor

{'s1a': 5, 's1b': 10, 's2a': 15, 's2b': 15, 's3': 20, 's4': 10, 's5': 20}

# Load Jawaban

In [4]:
jawaban_file = dfile ("data/jawaban")
jawaban_file

dict_jawaban_file = dict(zip(kode, jawaban_file))
dict_jawaban_file

{'s1a': 's1a.xlsx',
 's1b': 's1b.xlsx',
 's2a': 's2a.xlsx',
 's2b': 's2b.xlsx',
 's3': 's3.xlsx',
 's4': 's4.xlsx',
 's5': 's5.xlsx'}

# Load Library AES

In [5]:
from aes_class import AES
hasil_dict = dict()

# Parameter

In [6]:
tf=True
qe=False
ngram=True
n=1
stemming=True
binary = False

# tf=tf, qe=qe, ngram=ngram, n=n, stemming=stemming, binary = binary

## S1a

In [7]:
#Tanpa QE
model=  AES.AES(tf=tf, qe=qe, ngram=ngram, n=n, stemming=stemming, binary = binary)#otak atik disini
model.train([dict_kunci_jawaban['s1a']], [dict_skor['s1a']])

df = pd.read_excel("data/jawaban/"+dict_jawaban_file['s1a'])
jawaban = df.jawaban.tolist()
dickt = dict()

sim_list = list()
for j in jawaban:
    model.predict(j)
    similarity = model.hasil_cosine_similarity
    sim_list.append(similarity[0])
    print(".",end=".")
hasil_dict.update({"s1a":sim_list})
dickt.update({"s1a":sim_list})

#Menggunakan QE
model=  AES.AES(tf=tf, qe=qe, ngram=ngram, n=n, stemming=stemming, binary = binary)#otak atik disini
model.train([dict_kunci_jawaban['s1a']], [dict_skor['s1a']])

df = pd.read_excel("data/jawaban/"+dict_jawaban_file['s1a'])
jawaban = df.jawaban.tolist()


sim_list = list()
for j in jawaban:
    model.predict(j)
    similarity = model.hasil_cosine_similarity
    sim_list.append(similarity[0])
    print(".",end=".")
hasil_dict.update({"s1a_QE":sim_list})
dickt.update({"s1a_QE":sim_list})
pd.DataFrame.from_dict(dickt)

tf ngram
....................................................................................tf ngram
....................................................................................

         s1a    s1a_QE
0   0.417533  0.417533
1   0.515779  0.515779
2   0.451414  0.451414
3   0.455661  0.455661
4   0.414259  0.414259
5   0.276172  0.276172
6   0.494718  0.494718
7   0.667417  0.667417
8   0.471041  0.471041
9   0.759935  0.759935
10  0.397187  0.397187
11  0.719646  0.719646
12  0.684664  0.684664
13  0.455661  0.455661
14  0.336146  0.336146
15  0.390567  0.390567
16  0.300658  0.300658
17  0.506316  0.506316
18  0.781419  0.781419
19  0.361079  0.361079
20  0.803430  0.803430
21  0.393654  0.393654
22  0.429601  0.429601
23  0.444102  0.444102
24  0.695545  0.695545
25  0.303774  0.303774
26  0.390567  0.390567
27  0.390567  0.390567
28  0.546793  0.546793
29  0.457124  0.457124
30  0.746230  0.746230
31  0.276172  0.276172
32  0.470605  0.470605
33  0.000000  0.000000
34  0.487122  0.487122
35  0.517318  0.517318
36  0.701536  0.701536
37  0.375823  0.375823
38  0.431788  0.431788
39  0.225494  0.225494
40  0.429601  0.429601
41  0.504593  0.504593

# S1b

In [8]:
#tanpa QE
kode = 's1b'
dickt = dict()
model=  AES.AES(tf=tf, qe=qe, ngram=ngram, n=n, stemming=stemming, binary = binary)#otak atik disini
model.train([dict_kunci_jawaban[kode]], [dict_skor[kode]])

df = pd.read_excel("data/jawaban/"+dict_jawaban_file[kode])
jawaban = df.jawaban.tolist()


sim_list = list()
for j in jawaban:
    model.predict(j)
    similarity = model.hasil_cosine_similarity
    sim_list.append(similarity[0])
    print(".",end=".")
hasil_dict.update({kode:sim_list})
dickt.update({kode:sim_list})

#Menggunakan QE
model=  AES.AES(tf=tf, qe=qe, ngram=ngram, n=n, stemming=stemming, binary = binary)#otak atik disini
model.train([dict_kunci_jawaban[kode]], [dict_skor[kode]])

df = pd.read_excel("data/jawaban/"+dict_jawaban_file[kode])
jawaban = df.jawaban.tolist()


sim_list = list()
for j in jawaban:
    model.predict(j)
    similarity = model.hasil_cosine_similarity
    sim_list.append(similarity[0])
    print(".",end=".")
hasil_dict.update({kode+"_QE":sim_list})
dickt.update({kode+"_QE":sim_list})
pd.DataFrame.from_dict(dickt)

tf ngram
....................................................................................tf ngram
....................................................................................

         s1b    s1b_QE
0   0.414370  0.414370
1   0.551943  0.551943
2   0.319546  0.319546
3   0.490970  0.490970
4   0.619270  0.619270
5   0.376638  0.376638
6   0.443912  0.443912
7   0.393781  0.393781
8   0.435385  0.435385
9   0.464099  0.464099
10  0.434012  0.434012
11  0.444682  0.444682
12  0.389742  0.389742
13  0.327645  0.327645
14  0.309399  0.309399
15  0.397779  0.397779
16  0.533676  0.533676
17  0.990639  0.990639
18  0.477334  0.477334
19  0.540042  0.540042
20  0.378105  0.378105
21  0.512121  0.512121
22  0.422275  0.422275
23  0.159111  0.159111
24  0.159111  0.159111
25  0.337526  0.337526
26  0.368271  0.368271
27  0.354363  0.354363
28  0.000000  0.000000
29  0.469147  0.469147
30  0.318223  0.318223
31  0.411291  0.411291
32  0.463886  0.463886
33  0.570524  0.570524
34  0.411291  0.411291
35  0.318223  0.318223
36  0.426853  0.426853
37  0.473153  0.473153
38  0.516226  0.516226
39  0.552407  0.552407
40  0.551943  0.551943
41  0.498004  0.498004

In [9]:
#tanpa QE
kode = 's2a'
dickt = dict()
model=  AES.AES(tf=tf, qe=qe, ngram=ngram, n=n, stemming=stemming, binary = binary)#otak atik disini
model.train([dict_kunci_jawaban[kode]], [dict_skor[kode]])

df = pd.read_excel("data/jawaban/"+dict_jawaban_file[kode])
jawaban = df.jawaban.tolist()


sim_list = list()
for j in jawaban:
    model.predict(j)
    similarity = model.hasil_cosine_similarity
    sim_list.append(similarity[0])
    print(".",end=".")
hasil_dict.update({kode:sim_list})
dickt.update({kode:sim_list})

#Menggunakan QE
model=  AES.AES(tf=tf, qe=qe, ngram=ngram, n=n, stemming=stemming, binary = binary)#otak atik disini
model.train([dict_kunci_jawaban[kode]], [dict_skor[kode]])

df = pd.read_excel("data/jawaban/"+dict_jawaban_file[kode])
jawaban = df.jawaban.tolist()


sim_list = list()
for j in jawaban:
    model.predict(j)
    similarity = model.hasil_cosine_similarity
    sim_list.append(similarity[0])
    print(".",end=".")
hasil_dict.update({kode+"_QE":sim_list})
dickt.update({kode+"_QE":sim_list})
pd.DataFrame.from_dict(dickt)

tf ngram
....................................................................................tf ngram
....................................................................................

         s2a    s2a_QE
0   0.549762  0.549762
1   0.658323  0.658323
2   0.172774  0.172774
3   0.677674  0.677674
4   0.712691  0.712691
5   0.562978  0.562978
6   0.259161  0.259161
7   0.600284  0.600284
8   0.576023  0.576023
9   0.600994  0.600994
10  0.488678  0.488678
11  0.163908  0.163908
12  0.518321  0.518321
13  0.122169  0.122169
14  0.172774  0.172774
15  0.549762  0.549762
16  0.259161  0.259161
17  0.979535  0.979535
18  0.540867  0.540867
19  0.304953  0.304953
20  0.000000  0.000000
21  0.273179  0.273179
22  0.609513  0.609513
23  0.122169  0.122169
24  0.518321  0.518321
25  0.518321  0.518321
26  0.368355  0.368355
27  0.710266  0.710266
28  0.651570  0.651570
29  0.598506  0.598506
30  0.237186  0.237186
31  0.299253  0.299253
32  0.431934  0.431934
33  0.604708  0.604708
34  0.399004  0.399004
35  0.259161  0.259161
36  0.549762  0.549762
37  0.598506  0.598506
38  0.626203  0.626203
39  0.570124  0.570124
40  0.564276  0.564276
41  0.691095  0.691095

In [ ]:
#tanpa QE
kode = 's2b'
dickt = dict()
model=  AES.AES(tf=tf, qe=qe, ngram=ngram, n=n, stemming=stemming, binary = binary)#otak atik disini
model.train([dict_kunci_jawaban[kode]], [dict_skor[kode]])

df = pd.read_excel("data/jawaban/"+dict_jawaban_file[kode])
jawaban = df.jawaban.tolist()


sim_list = list()
for j in jawaban:
    model.predict(j)
    similarity = model.hasil_cosine_similarity
    sim_list.append(similarity[0])
    print(".",end=".")
hasil_dict.update({kode:sim_list})
dickt.update({kode:sim_list})

#Menggunakan QE
model=  AES.AES(tf=tf, qe=qe, ngram=ngram, n=n, stemming=stemming, binary = binary)#otak atik disini
model.train([dict_kunci_jawaban[kode]], [dict_skor[kode]])

df = pd.read_excel("data/jawaban/"+dict_jawaban_file[kode])
jawaban = df.jawaban.tolist()


sim_list = list()
for j in jawaban:
    model.predict(j)
    similarity = model.hasil_cosine_similarity
    sim_list.append(similarity[0])
    print(".",end=".")
hasil_dict.update({kode+"_QE":sim_list})
dickt.update({kode+"_QE":sim_list})
pd.DataFrame.from_dict(dickt)

tf ngram
..............................

In [ ]:

def percobaan(kode, )
    #tanpa QE
    kode = kode
    dickt = dict()
    model=  AES.AES(tf=tf, qe=qe, ngram=ngram, n=n, stemming=stemming, binary = binary)#otak atik disini
    model.train([dict_kunci_jawaban[kode]], [dict_skor[kode]])

    df = pd.read_excel("data/jawaban/"+dict_jawaban_file[kode])
    jawaban = df.jawaban.tolist()


    sim_list = list()
    for j in jawaban:
        model.predict(j)
        similarity = model.hasil_cosine_similarity
        sim_list.append(similarity[0])
        print(".",end=".")
    hasil_dict.update({kode:sim_list})
    dickt.update({kode:sim_list})

    #Menggunakan QE
    model=  AES.AES(tf=tf, qe=qe, ngram=ngram, n=n, stemming=stemming, binary = binary)#otak atik disini
    model.train([dict_kunci_jawaban[kode]], [dict_skor[kode]])

    df = pd.read_excel("data/jawaban/"+dict_jawaban_file[kode])
    jawaban = df.jawaban.tolist()


    sim_list = list()
    for j in jawaban:
        model.predict(j)
        similarity = model.hasil_cosine_similarity
        sim_list.append(similarity[0])
        print(".",end=".")
    hasil_dict.update({kode+"_QE":sim_list})
    dickt.update({kode+"_QE":sim_list})
    return pd.DataFrame.from_dict(dickt)

In [14]:
pd.DataFrame.from_dict(hasil_dict)

,s1a,s1a_QE,s1b_QE,s1b,s2a_QE,s2a,s2b_QE,s2b
0,0.417533,0.442642,0.402524,0.414370,0.546358,0.549762,0.538993,0.538993
1,0.515779,0.531494,0.510593,0.551943,0.669498,0.658323,0.323029,0.323029
2,0.451414,0.500719,0.427681,0.319546,0.184177,0.172774,0.240772,0.240772
3,0.455661,0.455661,0.484945,0.490970,0.677674,0.677674,0.635223,0.635223
4,0.414259,0.414259,0.641035,0.619270,0.704260,0.712691,0.467446,0.467446
5,0.276172,0.288185,0.421702,0.376638,0.562978,0.562978,0.347524,0.486534
6,0.494718,0.506866,0.564846,0.443912,0.259161,0.259161,0.318511,0.300965
7,0.667417,0.667417,0.437557,0.393781,0.600284,0.600284,0.196589,0.196589
8,0.471041,0.505511,0.568794,0.435385,0.622239,0.576023,0.538993,0.601003
9,0.759935,0.756525,0.464075,0.464099,0.561979,0.600994,0.625943,0.581232
10,0.397187,0.397187,0.522304,0.434012,0.522419,0.488678,0.530852,0.507856
11,0.719646,0.731190,0.461115,0.444682,0.199502,0.163908,0.497336,0.521672
12,0.684664,0.667638,0.389742,0.389742,0.508256,0.518321,0.425628,0.425628
13,0.455661,0.473632,0.363121,0.327645,0.122169,0.122169,0.120386,0.120386
14,0.336146,0.336146,0.377890,0.309399,0.299253,0.172774,0.120386,0.120386
15,0.390567,0.390567,0.398815,0.397779,0.546358,0.549762,0.255377,0.255377
16,0.300658,0.300658,0.539862,0.533676,0.282138,0.259161,0.240772,0.240772
17,0.506316,0.535202,0.990639,0.990639,0.979535,0.979535,0.987785,0.987785
18,0.781419,0.781419,0.469194,0.477334,0.527107,0.540867,0.540621,0.540621
19,0.361079,0.340915,0.509843,0.540042,0.342074,0.304953,0.120386,0.120386
20,0.803430,0.791486,0.428482,0.378105,0.000000,0.000000,0.631309,0.599205
21,0.393654,0.370524,0.526371,0.512121,0.273179,0.273179,0.510754,0.510754
22,0.429601,0.459334,0.543201,0.422275,0.631012,0.609513,0.500835,0.500835
23,0.444102,0.477359,0.159111,0.159111,0.199502,0.122169,0.323029,0.323029
24,0.695545,0.683293,0.159111,0.159111,0.493742,0.518321,0.479914,0.445428
25,0.303774,0.329355,0.337526,0.337526,0.493742,0.518321,0.400668,0.400668
26,0.390567,0.397187,0.398815,0.368271,0.368355,0.368355,0.170251,0.170251
27,0.390567,0.344447,0.517321,0.354363,0.710266,0.710266,0.611315,0.567613
28,0.546793,0.546793,0.000000,0.000000,0.651570,0.651570,0.196589,0.196589
29,0.457124,0.480113,0.505247,0.469147,0.618134,0.598506,0.240772,0.240772
30,0.746230,0.722484,0.318223,0.318223,0.296304,0.237186,0.427327,0.403786
31,0.276172,0.300658,0.515887,0.411291,0.323230,0.299253,0.494902,0.486534
32,0.470605,0.485111,0.463886,0.463886,0.493742,0.431934,0.283752,0.290382
33,0.000000,0.000000,0.577300,0.570524,0.644635,0.604708,0.323029,0.323029
34,0.487122,0.499615,0.489203,0.411291,0.399004,0.399004,0.481543,0.120386
35,0.517318,0.556221,0.505247,0.318223,0.309067,0.259161,0.340503,0.340503
36,0.701536,0.701536,0.490983,0.426853,0.406604,0.549762,0.508168,0.508168
37,0.375823,0.390567,0.469896,0.473153,0.503718,0.598506,0.627036,0.627036
38,0.431788,0.436990,0.525637,0.516226,0.643790,0.626203,0.417029,0.481543
39,0.225494,0.260378,0.551293,0.552407,0.579501,0.570124,0.571040,0.553317
40,0.429601,0.492068,0.510593,0.551943,0.442026,0.564276,0.494902,0.540621
41,0.504593,0.533933,0.489632,0.498004,0.691095,0.691095,0.556038,0.556038